apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:CqgW+EI4zgRe1UT9k5fV0dcLHeVs5cAUxB+0NF23Za0hirKEN16thyBsK6qgJFCItjPfy9v9PVDHXnRMz7Gcu2Upxo/wQSbzmGuWQj+ZXJKLsbf0WhqSN9dRzHzWyDf030uj014A4JB9Uhc/cP/gquFCvcucaMpDuJ933099n0uFx8ESs6e6ibL7RoP9HRwTp799f5D5DLGT9giwTVusDdpjuXan5jSpTDqQL5GhE1imLfqvfcOm/hXgQZVSTAHC1+DCY/30jUysheA56DKzsfP2DJjGZxNGXQP1frrosJqZng2QIc1nVbALTYg=,iv:UlRMSnSe5gbChLMMrJJVrCRR52aiHvMnv7DLclL2m+I=,tag:aaJc1XucDHs7Tdzr2ycnRw==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaWklPOUhibUdUM2NCU3Z0
            SFR2SjFoVjRXQzNvQkpIUVRqblVYT0ZhN1RzCkZjbUQ0dTRyaTE0eDBhWjdVZ3Fs
            bGJtYTVmZG5TT2d0bVF3VlZFd1RTajAKLS0tIEFRUDJiTjNCVnpjN1FNZGlzQkE5
            Ykt2dGw1LzNpaXRwVFphZ2xZSDc2R0UKmonwmx128E0zpUoa50VJwnOWBLmOvyDs
            bE/Yf/G3Qc23dGeM41XDjEgIbwwDrJI8HQSMq6TMqYjS1J23friO2g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1w8unfcd33dkuag6zzwgsxfpc9sux5lt7q4pseaa806jhcgknwy6q2qe3yw
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-08T21:38:46Z"
    mac: ENC[AES256_GCM,data:v3vluC8W4/vBEhOkUkMFEUhRz2cHN1wG+KyaVL/AmBMTD+43JU4dIKM8WhiYfAsu8tZrohv8yOtx8CjxvLRTDeCRJjuqlCwJ4yxwbWoSOxddwlkXwF1QCCH/dlvpXJRPSJL3ei+nFYkmXrUTLolCcTQQOCVQatbT89fOrwu224Q=,iv:0wfqeMk0JsFirS+u53BLqE5EoUufWHzNmBjBa+qwis0=,tag:NBGkhNYWxyqoWwk9I/UbMw==,type:str]
    version: 3.13.2
