apiVersion: v1
stringData:
    ABS_SUPER_PASSWORD: ENC[AES256_GCM,data:rV+CJ0RSMxssMP//xxE1NEdgS8kxuC5r,iv:TP2w7AtDY0+CVnTMa3TBVVM2a6r/bVZVbWT4a5flpZA=,tag:hMx1OaDEXNYpWtzsJG3IFQ==,type:str]
    ABS_SUPER_USER: ENC[AES256_GCM,data:xd4tYmAZFto=,iv:GmctqBEUs+lya2OM5T+w0BU1qnWz2Ffqt+MvYKr62B4=,tag:n83Xqy4ljab1thTQAZHVZQ==,type:str]
kind: Secret
metadata:
    name: audiobookshelf-secret
    namespace: audiobookshelf
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQT0J6cjVuM2lHQkFFMmV3
            Z2N5K2lZS0R0Skl0ek1LNlVJTldjY1RMalV3ClNvanVLcjlBL1pFYmZPTlZoZFJr
            aTVJb2lHS21ocC9MUVNDVkRDL2M0RkEKLS0tIGZCc0k1OXp5bmdNWlR4VWpzMEFv
            NXM5SEIzU0c3NE5Cd2ZOSzNvYzlkODgKnupEZwtove6W/NRbVKk/1nqGHXkMCZZd
            fNtzVaknzXuzS14wFvs+Mmvsw959H2VDJZU9SGgY1k0nay6YzBSerQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1w8unfcd33dkuag6zzwgsxfpc9sux5lt7q4pseaa806jhcgknwy6q2qe3yw
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-08T21:01:10Z"
    mac: ENC[AES256_GCM,data:4XYrHA50wuBlfwDV19iKw7GMa9QciTliwoswFqmehzt2Q3L77UkgGdJI+xjIRxrhZ2Bf48YzwrdTjHtFRcmAHfz9n+7Bp1cM8he84lhtSq8WGgQgWK6a66DTnabUUe1Jnri5Gs+hE1GF6yROzgqXf+Q6Rqh3g+Oiz+11RMfr4tk=,iv:imBunEmxZz8jSzt1kq2ck9GA8Sin891T2hBLYIE590Q=,tag:Ajx4w+4B86ff/VYfnbEP1g==,type:str]
    version: 3.13.2
