apiVersion: v1
data:
    password: ENC[AES256_GCM,data:bUo+NbutokFWK1hMUxoQ9YyR7Kc=,iv:1qbu76hpS+rIgK6bkpYKeZLPpUEX0MjSbqgOTcQw9lk=,tag:CSstofbvUbTO6Z4XIgGcQg==,type:str]
    user: ENC[AES256_GCM,data:VGlm7OGTgUE=,iv:Lwq2mdgvTN5Hkw2cI2LDY1An8+BV6Gqry4Xh6oIBDXk=,tag:SdAk6EgtGLaNIMmJMw+HAw==,type:str]
kind: Secret
metadata:
    name: test-secret
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTb0s2ajBJdi9JbHgyWTFJ
            eENwZm9BTSs2YTBldVM5TUNKaWE5ZUdKaWdrCnJMYWQzNFdKOVRSVENsT3BHaGs2
            cHdRWkkzcy9yeVpXM2h1QWkvRndrRDQKLS0tIDVZUm1BY1pCejl3NUdIRks1ZGs2
            LzMzc0dTRVdNalJ3ZWNITFRHaDljd3cKMsrQuv0AExEYW2jiKUdxSh6DuNWItdVq
            ySyP/YFjJk7EC9xbb1Y9YGmSY4u/3DLHvI0C/z4q0RGK0dwz9qNGuA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1w8unfcd33dkuag6zzwgsxfpc9sux5lt7q4pseaa806jhcgknwy6q2qe3yw
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-07T01:12:33Z"
    mac: ENC[AES256_GCM,data:YwQQ9z+Xph96IWIIE0v6QHDMwmuH1nkEg39JgXJ715jEofMYhQN7+beV8b/Oio7tDdrL/vdCktIQBScgSh6EQTMN/UIKJPpqxevi1rvWeqBbCj2HrBYhYYB5TF+2QygHHzAMUyCUXJ0e9o3NfO/Xl8ceUOaIXJCPmeyCsAFhkpo=,iv:JA3po9Igsg0rpwodOt6m/WHdecFLU0VPqrhUWy/x9zQ=,tag:5fU+NgJZNRbfoz3Ah9N46w==,type:str]
    version: 3.13.2
