apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:QP/egowrkuqABXqBgIg0k1S8ABSIVP9JVL0mHnK2q1HHjG1j5oy6ihnCqsx44jdXBh3iPUh1u0j1EBBGSzCjPljI0GujAvayUc9XMjyeYWvpnVvmtezQLahckGK+We0NRJ+I+N6DNyM/GhYyIeL/WVwxsKdqUHxewrabr/WCq+NtLL+is9uXDHhOfj+kScfROPxQ6Qks5nPLfCnHUNwL9Z/ytAz9Tac0NfLmcim44wLcb+CQ1cjQIQQ74u7uGU9wtlKfuBsEzJIEi6xS37rTRBbpYRqe/7M+YVn3VQMbyR2wxdlidW2QWtxau6c=,iv:v5V966qH2Hd/R+TfXvLQlNG1PTi8U0viViZ77e4Z6Cg=,tag:nSAZ8/uTUXlhnX72ickuiw==,type:str]
kind: Secret
metadata:
    creationTimestamp: "2026-07-04T00:49:02Z"
    name: tunnel-credentials
    namespace: linkding
    resourceVersion: "22691"
    uid: d3f3fd72-b5eb-477b-b58e-858175372b70
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwQkplblhMTnlHL0tCTXhM
            Smh4bk0xOGRERzd5MUZrdzRpVldYVWEyTlJNCnN1WEpHVmVqSDdJbGlNRG1oZ1pj
            VXVTS3pvWm03bHZPRThDSUhXd04yZmcKLS0tIGhtQ3YvYXNmZ25TcG1FZXJ1UWE5
            L2xLQ0xlYjFnMUdoMms3WEd3MGo3UVkKcvu7XIwwX29cDGkVKLH0fqDMwnpVK2/5
            A6OAMFi/8J5bktwSFdv7f6gfnn0lrFiA2/4o313pG0YwzS92VXTq9w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1w8unfcd33dkuag6zzwgsxfpc9sux5lt7q4pseaa806jhcgknwy6q2qe3yw
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-07T02:57:42Z"
    mac: ENC[AES256_GCM,data:hYjRERpYX53xFEuzZj6Qc/6uGPAuZGEtCawk4lEgcEKiw7gLuUwysf0shqd5gQtBrSswIB7uG2+jbz/F+bWEMUkWaHnz7U683tryJBZRlS2Av6DeO3sjwctBzXrzz1VhPDUpQafPdlspYrDNKmTdS5GLwLxA9tM9GmLWpSGnvhQ=,iv:whoai9Jt6U6vzpNaO6Cexp4Vr5Hwc2rgAaG48bl/7jQ=,tag:bs4PZpa5hovRcZ4EnANi+w==,type:str]
    version: 3.13.2
