apiVersion: v1
data:
    NAS-info.yaml: ENC[AES256_GCM,data:qiIpK/SZ4SVRNx96Ewi8/1KMQkZ7zrIQ6m1yUBhoASMnYv79PFiBgZxWtMh3vkgNWXnm2xWDCHftPdjrYi3X1YMpnn5IupW5QbrPXgjU0Y1cqcgxSyFMPR/yGYg9QCR8RBO8zSrLWzOXj75n3YHYX7deeaociRGNpoFMyBfzYgwmFduobYlDnDSHy/SslJDqoRv4+ptUPIYWDmEy46HPHw==,iv:ZtS5hPwQfLwgBI1MgDgXejHK3cAF7pWwGokfihH117Y=,tag:NartXF5nkhvJ6Rj7r7iy2g==,type:str]
kind: Secret
metadata:
    name: NAS-info.yaml
    namespace: synology-csi
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZdGVBdVVpaWYzcDZLamlY
            ZUQvL09QNE9JMnRHZUt3T3RYS2Z5QWI0TVZzCkR0bHNyVEt3eVNSbHFjVzhrY1pB
            VjJFUmFZOTRaTTRPZkRTc2NNTHdVMkEKLS0tIHlXUkYvem01SThBcUxsT3pySDdY
            czdoWmdOLzl5ZnFDNVJ2OTRuWFBVUXMKcgmrFi9rbHOc7C6MowYj0jwwa9/qYK0n
            b/9N/KQ10BtuB14PopLLv83J2aYhKWMvODLlos4NL1DLFDVTBmgOtw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1w8unfcd33dkuag6zzwgsxfpc9sux5lt7q4pseaa806jhcgknwy6q2qe3yw
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-15T21:47:15Z"
    mac: ENC[AES256_GCM,data:aAIru/GTIM7RaEwA/lARe1Wp2ZplTte30xMEiZ8+N7JLkTXBFul2UZqHyGRlCRdQvmwOkQrlD37x1MjvfCrmcMWrKQMCyA5Kk0aUDRHrtVc4UMV5XdUX2cB3F+SGL07D4KjiNd3aWGdLr4/fsIeEjaj7+PEOAjcorxFeUkOgE58=,iv:DkhpecEH3yDAkAExi8hAXYZzxrZizDIM2k17gcwwtmk=,tag:uCOIwGpURuihKOHN52uvAA==,type:str]
    version: 3.13.3
