apiVersion: v1
data:
    cilent-info.yaml: ENC[AES256_GCM,data:W6LiW7OOzJtlQV5GUPorDqp4nJCe3Odjf4vBnuxqQdOXb176y75+V/Pz9c0QAjG1O1N3tHJoOw1MoF1teuMGEPwPpgY3oy+Zxi6IzVJceS6tzUU+5ugUONUQswdcFpUMN23IOAsVA/ZonKEU7EQ6MB+qFuwLDWP5K8ppfy6sD/+iSfAVRLdWk1hxgNLpTd0GRiTprbXaablRay/EdnKsIg==,iv:N7Jwm19L+UHkpRhPo8zuWzNH9qgzSK2Rw2KmlKpAj1M=,tag:jQbVrpDQqU/AZCHgbRwyJQ==,type:str]
kind: Secret
metadata:
    name: synology-info-secret
    namespace: synology-csi
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLdi9zeGlyVThDdU9Fa2t5
            bWhqekpKZGdJcmo1SU14OXRST0U2QXQ2clJ3CkF5SFJFRGd5a2l2aTloWXdrUnZh
            M3dlQ3piKzFmamFOdGNmL3F4bmZkWUEKLS0tIDJzak1NSytBNnFna0MrUndYc0Q3
            THR6QVhSa2ZZek9PU0ZuV2g2SlVzNHMKDvr1+Nw+YcYaiJlzXk++S03H05hDnSPa
            6oQtDotObK+YkSQ/RSq8dzn68VHx9SxtkSq0yHxBLl5TmyvKruGijQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1w8unfcd33dkuag6zzwgsxfpc9sux5lt7q4pseaa806jhcgknwy6q2qe3yw
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-16T00:15:38Z"
    mac: ENC[AES256_GCM,data:79eBG2RV0p5XuWiZ7gLq1F0gj+93qiSovQqHfKe5EaJwORU4qj105nN52R34/0Ce1UItRIy7FfVd56wm1QT8n4wQ6Fd1+3fnB2nycOL4Dc30dVMdTXIuiLH+Sn1RNLOsGRh7PNKAFzG9kcI53ouxQDfmMigpoYMCXOq9PLY3grc=,iv:Wp7ZuYR6f4P1Iw9SXl/uWYXMGmoK9waSCs9CaTLZzAI=,tag:eZi6F6ThAxVoGPX0SkCnwQ==,type:str]
    version: 3.13.3
