apiVersion: v1
data:
    NAS-info.yaml: ENC[AES256_GCM,data:IwA4YJMm6GzyaChqGlJdEv7zlHDIMworJ+4y4PMKk7az4GJc6nmxA4fSpeiK30z7RNzrIDWXKllKuz63wAV6Q4No3fMr5C9tMAXhYVKJ5MXO1OzeEGWCkcX+1qsPTv60hbC6Sd4vEQVisqAUM2ZezPD+cTdvHs1tdKkqA26Xh1bwAMHls4dk1RC/VMO1Ni9hxI3aelP110raYCfaSBeaTA==,iv:R79yAHKmiMGBn2r2W2hKcEMlnjouPkdMnGVy+V1hVZ4=,tag:zkavGrwN+oKr+gikQQCSDA==,type:str]
kind: Secret
metadata:
    name: synology-info-secret
    namespace: synology-csi
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxSVJYSlliU1hBeHdlVkZP
            dm1XN1Z0aXBuMzZhbmhyZzQzV3N1a1E5ekV3CnFVbzBrdUd2T3BrZnAwemd5ODB0
            YUZhenIvQ1ZtY203STU3cTY2N2JUUzAKLS0tIG0yOE82N0xjYUF0RUkzbGlMRzhX
            bDBOWTMrVmo0OGRVYXlpRDM1QjgzUHcKB7hN9Xm5cwRV4wlbAWF45F/+oHhuaVtR
            E5rapC9QegOmzuhCThYsRodRsBp6ekyF++DCskILHuj/r/RQzF11EQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1w8unfcd33dkuag6zzwgsxfpc9sux5lt7q4pseaa806jhcgknwy6q2qe3yw
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-15T23:55:56Z"
    mac: ENC[AES256_GCM,data:oI4y32I/r7Y85G/cTqYkthMib0YqM7ETvwZzw/gJtb3ekfMWP5p/MWLEwCCdra0yrLN4gG39I6IAMhXA2fcI1eg8RCcTd3qeG9e+xRtrCNwkflNB4s0ipwpm2tIFOqvEftq0VsnsnFKn0ujKPNfJ9Jh3deEw6MTpoJB+U+fMu/c=,iv:A+KQGScQBo4g2rXNijrbRTcO5QQfGHuscGVaFNhRhFw=,tag:oAXv0PosHZdcflbszyandQ==,type:str]
    version: 3.13.3
