apiVersion: v1
data:
    client-info.yaml: ENC[AES256_GCM,data:vLhxrJ8KhmCiGFzUicX1UmauJ8h5ah0dSzZc9GBPLdiGq5+qRCTNDJarMhqMvfzblTnDFEiBFogU43VntU7Og+JeJd/UtR6T5JIqgwlaihCKavfMZwNq+1deeJnGYRc1i3017qBgSAtvspc5t3ZQ6iJd/tnJhrz0zcWv1xlSuIjuv5pHh48g/1LLLXJuf99Q/qWBr8PHG5WpgM8D72S9nQ==,iv:l9X4ib9ZjjG2BtxXcvT//yQUvp5svc5u/ZertM0inw8=,tag:qqYojROxsY+KPKn+2jnI/g==,type:str]
kind: Secret
metadata:
    name: synology-info-secret
    namespace: synology-csi
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1bUYxZklHSmxtbkdwZnRN
            b2hmSnNXTjVOQVJMMFlwVEJaTzV4Z3NXMTNnCkNSVDhOTW0vakpRSzRWL2REYkFp
            aWZHaG90UEx2ZDVMK0c4NFpKRjNmQUkKLS0tIFFiVWFkWFNDV1JhOU9PNkFNZ0Y0
            Kzd1dEsvRGhiY3FEbWorUjBVLzlacDgKr8Ixla6hk794zdIuAFeaoizVVQKMVI3C
            FFJ9gAoX5JlZTOscys0GHpNaDF3qii4qPRxyyp7O2sACYrPwb6ljGQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1w8unfcd33dkuag6zzwgsxfpc9sux5lt7q4pseaa806jhcgknwy6q2qe3yw
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-16T00:31:00Z"
    mac: ENC[AES256_GCM,data:qU7QiEs5rWhBcbryU2icmE17G3Xi6erkrRa4fDm7iROzknbbQdy1jQ9Qg9NkL5FT7TEkZqiAaPWXph0ssOvu9TCa4A8HWaIvPDdmgtTbCUoc6hcH6657FdRqxgvKJmgmGnrEtaNvGBVW6km1rzQDXVEUNwuMIQWLXKbSEtQ85gk=,iv:ACHxYOifICjab6QRX1j7LnVDb/7omtGPNoXUs9paBqE=,tag:N5KtNU+H+3rcZ3pZ9oDCBQ==,type:str]
    version: 3.13.3
